### ISSUE TITLE
User Story Example Acceptance criteria and tasks

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/Love-Running#3]
In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response.

# Criteria:

* The option should be provided as a checkbox
* The checkbox should be “checked” by default
* The option should appear next to the submit button
* After submitting the default submission confirmation should be adjusted to include the user name.

# Tasks

- [ ] #4
- [ ] Select where to place it in the poll form
- [ ] Create HTML and CSS code
- [ ] Checked by default
#3
