### ISSUE TITLE
EPIC - User Poll

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/Love-Running#5]
# 1.User Story

In order to provide opinion about a certain topic as a runner, I can select and submit and answer from the poll

## Acceptance criteria:
  * Poll must contain 3/4 especific answers for the user to select
  * Answers will be selected trough a checkbox
  * Submit button will submit all the answers together 

# 2.User Story

In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response.

# Criteria:

* The option should be provided as a checkbox
* The checkbox should be “checked” by default
* The option should appear next to the submit button
* After submitting the default submission confirmation should be adjusted to include the user name.

# Tasks

- [ ] #4
- [ ] Select where to place it in the poll form
- [ ] Create HTML and CSS code
- [ ] Checked by default
