### ISSUE TITLE
User Story: Creat a poll

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/Love-Running#6]
# 1.User Story

In order to provide opinion about a certain topic as a runner, I can select and submit and answer from the poll

## Acceptance criteria:
  * Poll must contain 3/4 especific answers for the user to select
  * Answers will be selected trough a checkbox
  * Submit button will submit all the answers together 
 
## Tasks

- [ ] Choose questions and possible answers
- [ ] Design poll layaout in the Homepage
- [ ] Design checkbox for possible answers
- [ ] Design submit button
- [ ] Create HTML and CSS code
- [ ] Require all questions answered to be able to submit poll
- [ ] Design confirmation text after submitting poll
