### ISSUE TITLE
User Story: Hide users identity in the poll 

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/Love-Running#7]
# 2.User Story

In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response.

## Criteria:

* The option should be provided as a checkbox
* The checkbox should be “checked” by default
* The option should appear next to the submit button
* After submitting the default submission confirmation should be adjusted to include the user name.

## Tasks

- [ ] Design checkbox and related text 
- [ ] Select where to place it in the poll form
- [ ] Create HTML and CSS code
- [ ] Checked by default
- [x] #8
